name: example
description: A new Flutter project.
publish_to: 'none'
version: 2.0.6+69

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  version_check:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
