name: version_check
description: Check iOS/Android/Mac store version and provide update alert if update is available.
version: 0.7.3
#author: ChunKoo Park <mix1009@gmail.com>
homepage: https://github.com/mix1009/version_check

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.4
  http: ^1.2.1
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter: null
